from fpdf import FPDF
from datetime import datetime

class ProtocolPDF(FPDF):
    def header(self):
        # Logo or Title
        self.set_font('helvetica', 'B', 20)
        self.cell(0, 10, 'Laboratory Protocol', border=False, new_x="LMARGIN", new_y="NEXT", align='L')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} - Generated by Lab Assistant', align='C')

def create_protocol_pdf(protocol_name, final_volume, volume_unit, steps, hazards):
    """
    Generate a PDF for the protocol.
    
    Args:
        protocol_name (str): Name of the protocol
        final_volume (float): Total volume
        volume_unit (str): Unit (mL, L, etc.)
        steps (list): List of protocol step dictionaries
        hazards (list): List of hazard strings
        
    Returns:
        bytes: PDF file content
    """
    pdf = ProtocolPDF()
    pdf.add_page()
    
    # Metadata
    pdf.set_font("helvetica", "", 12)
    pdf.cell(0, 10, f"Protocol: {protocol_name}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 10, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 10, f"Final Volume: {final_volume} {volume_unit}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)
    
    # Safety Section
    if hazards:
        pdf.set_fill_color(255, 235, 238) # Light red background
        pdf.set_text_color(183, 28, 28)   # Dark red text
        pdf.set_font("helvetica", "B", 12)
        pdf.cell(0, 10, "SAFETY WARNINGS", fill=True, new_x="LMARGIN", new_y="NEXT", align='L')
        pdf.set_font("helvetica", "", 11)
        pdf.multi_cell(0, 8, f"This protocol involves: {', '.join(hazards)}. \nPlease ensure appropriate PPE (Gloves, Goggles, Lab Coat) is used.", fill=True, new_x="LMARGIN", new_y="NEXT", align='L')
        pdf.set_text_color(0, 0, 0)       # Reset to black
        pdf.ln(5)
    else:
        pdf.set_fill_color(232, 245, 233) # Light green
        pdf.set_text_color(27, 94, 32)    # Dark green
        pdf.set_font("helvetica", "B", 12)
        pdf.cell(0, 10, "NO KNOWN HAZARDS", fill=True, new_x="LMARGIN", new_y="NEXT", align='L')
        pdf.set_text_color(0, 0, 0)
        pdf.ln(5)
        
    # Steps Header
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "Procedure Steps", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    
    # Steps Table Header
    pdf.set_font("helvetica", "B", 10)
    pdf.set_fill_color(240, 240, 240)
    col_widths = [15, 60, 30, 85] # ID, Reagent, Amount, Notes
    
    pdf.cell(col_widths[0], 8, "#", border=1, fill=True)
    pdf.cell(col_widths[1], 8, "Reagent", border=1, fill=True)
    pdf.cell(col_widths[2], 8, "Amount", border=1, fill=True)
    pdf.cell(col_widths[3], 8, "Notes", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")
    
    # Steps Content
    pdf.set_font("helvetica", "", 10)
    for step in steps:
        pdf.cell(col_widths[0], 8, str(step['step_number']), border=1)
        pdf.cell(col_widths[1], 8, step['reagent'], border=1)
        pdf.cell(col_widths[2], 8, f"{step['amount']} {step['unit']}", border=1)
        pdf.cell(col_widths[3], 8, step.get('notes', ''), border=1, new_x="LMARGIN", new_y="NEXT")
        
    # Disclaimer
    pdf.ln(15)
    pdf.set_font("helvetica", "I", 8)
    pdf.set_text_color(128, 128, 128)
    pdf.multi_cell(0, 5, "Disclaimer: Reagent amounts and safety information should be verified before use. The authors assume no liability for experimental outcomes.", new_x="LMARGIN", new_y="NEXT")
    
    return bytes(pdf.output())
